---
title: "Resumo"
lang: "pt-br"
format: 
  html:
    css: style.css
  
editor: visual

execute:
  echo: false
  warning: false
---

## Estatísticas das seções em 2018 - 1º turno

```{r}

# leitura da base de dados
dados <- readr::read_csv2(
  file = here::here("data", "base_2018_01.csv"),
  locale = readr::locale(encoding = "latin1")
) |>
  janitor::clean_names() |>
  dplyr::filter(tipo == "bio", subs_urna == 0) |>
  dplyr::mutate(atraso =
                  ifelse(tempo_atraso >= lubridate::hms("01:00:00"), 1, 0)
                )



```

A @fig-histograma apresenta a distribuição dos eleitores dentro das seções que foram 100% biométricas em 2018, enquanto a @tbl-resumo_estat exibe estatísticas referentes a essas seções.

```{r}
#| fig-cap: "Distribuição dos aptos por seção com biometria em 2018"
#| fig-align: center
#| label: fig-histograma

dados |>
  ggplot2::ggplot(ggplot2::aes(x = qt_aptos)) +
  ggplot2::geom_histogram( fill = "steelblue", color = "white") +
  ggplot2::labs(x = "Eleitores aptos", y = "Frequência") +
  ggplot2::theme_minimal()

```

```{r}
#| label: tbl-resumo_estat
#| tbl-cap: "Estatísticas descritivas das seções com biometria na eleição de 2018"

#
resumo_estat <- dados |>
  dplyr::summarise(
    n_secoes = dplyr::n(),
    media_secao =  mean(qt_aptos, na.rm = TRUE),
    mediana_secao = median(qt_aptos, na.rm = TRUE),
    desvpad_secao = sd(qt_aptos, na.rm = TRUE),
    max_secao = max(qt_aptos, na.rm = TRUE),
    min_secao = min(qt_aptos, na.rm = TRUE),
  )

resumo_estat |> 
  gt::gt() |>
  gt::cols_align(align = "center") |>
  
  gt::cols_label(
    n_secoes = "Nº seções",
    media_secao = "Média/seção",
    mediana_secao = "Mediana/seção",
    desvpad_secao = "Desvio padrão",
    min_secao = "Eleitorado menor seção",
    max_secao = "Eleitorado maior seção",
  ) |> 
  gt::fmt_number(
    columns = 2:3,
    decimals = 2,
    dec_mark = ","
  ) |>
  gt::fmt_number(
    columns = 1,
    decimals = 0,
    dec_mark = ",",
    sep_mark = "."
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_column_labels()
  )


```

Na @fig-histograma_tempos podem ser vistos a distribuição dos tempos de atraso, medidos em segundos daquelas seções que utilizaram biometria em 2018.

```{r}

#| fig-cap: "Distribuição dos aptos por seção com biometria em 2018"
#| fig-align: center
#| label: fig-histograma_tempos

dados |>
  dplyr::mutate(tempo_atraso = as.numeric(lubridate::hms(tempo_atraso))/60) |> 
  ggplot2::ggplot(ggplot2::aes(x = tempo_atraso)) +
  ggplot2::geom_histogram( fill = "steelblue", color = "white", bins = 15) +
  ggplot2::labs(x = "Atraso encerramento votação (min)", y = "Frequência") +
  ggplot2::scale_x_continuous(breaks = seq(10, 90, by=10)) +
  ggplot2::theme_minimal()
```
